mkdir $(pwd)/packages/web3-core/node_modules
mkdir $(pwd)/packages/web3-core/node_modules
mkdir $(pwd)/packages/web3-net/node_modules
mkdir $(pwd)/packages/web3-shh/node_modules
mkdir $(pwd)/packages/web3-vns-personal/node_modules
mkdir $(pwd)/packages/web3/node_modules
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns-abi/node_modules/web3-utils
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns-iban/node_modules/web3-utils
ln -s $(pwd)/packages/web3-vns-iban $(pwd)/packages/web3-core-helpers/node_modules/web3-vns-iban
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-core-helpers/node_modules/web3-utils
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-core-subscriptions/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-providers-http/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-providers-ipc/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-providers-ws/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-core-method/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-promievent $(pwd)/packages/web3-core-method/node_modules/web3-core-promievent
ln -s $(pwd)/packages/web3-core-subscriptions $(pwd)/packages/web3-core-method/node_modules/web3-core-subscriptions
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-core-method/node_modules/web3-utils
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-core-requestmanager/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-providers-http $(pwd)/packages/web3-core-requestmanager/node_modules/web3-providers-http
ln -s $(pwd)/packages/web3-providers-ipc $(pwd)/packages/web3-core-requestmanager/node_modules/web3-providers-ipc
ln -s $(pwd)/packages/web3-providers-ws $(pwd)/packages/web3-core-requestmanager/node_modules/web3-providers-ws
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-core/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-core/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-core-requestmanager $(pwd)/packages/web3-core/node_modules/web3-core-requestmanager
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-core/node_modules/web3-utils
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-net/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-net/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-net/node_modules/web3-utils
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-shh/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-shh/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-core-subscriptions $(pwd)/packages/web3-shh/node_modules/web3-core-subscriptions
ln -s $(pwd)/packages/web3-net $(pwd)/packages/web3-shh/node_modules/web3-net
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-vns-contract/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-vns-contract/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-vns-contract/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-core-promievent $(pwd)/packages/web3-vns-contract/node_modules/web3-core-promievent
ln -s $(pwd)/packages/web3-core-subscriptions $(pwd)/packages/web3-vns-contract/node_modules/web3-core-subscriptions
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns-contract/node_modules/web3-utils
ln -s $(pwd)/packages/web3-vns-abi $(pwd)/packages/web3-vns-contract/node_modules/web3-vns-abi
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-vns-accounts/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-vns-accounts/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-vns-accounts/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns-accounts/node_modules/web3-utils
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-vns-personal/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-vns-personal/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-vns-personal/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-net $(pwd)/packages/web3-vns-personal/node_modules/web3-net
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns-personal/node_modules/web3-utils
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-vns-ens/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-vns-ens/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-promievent $(pwd)/packages/web3-vns-ens/node_modules/web3-core-promievent
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns-ens/node_modules/web3-utils
ln -s $(pwd)/packages/web3-vns-abi $(pwd)/packages/web3-vns-ens/node_modules/web3-vns-abi
ln -s $(pwd)/packages/web3-vns-contract $(pwd)/packages/web3-vns-ens/node_modules/web3-vns-contract
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3-vns/node_modules/web3-core
ln -s $(pwd)/packages/web3-core-helpers $(pwd)/packages/web3-vns/node_modules/web3-core-helpers
ln -s $(pwd)/packages/web3-core-method $(pwd)/packages/web3-vns/node_modules/web3-core-method
ln -s $(pwd)/packages/web3-core-subscriptions $(pwd)/packages/web3-vns/node_modules/web3-core-subscriptions
ln -s $(pwd)/packages/web3-net $(pwd)/packages/web3-vns/node_modules/web3-net
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3-vns/node_modules/web3-utils
ln -s $(pwd)/packages/web3-vns-abi $(pwd)/packages/web3-vns/node_modules/web3-vns-abi
ln -s $(pwd)/packages/web3-vns-accounts $(pwd)/packages/web3-vns/node_modules/web3-vns-accounts
ln -s $(pwd)/packages/web3-vns-contract $(pwd)/packages/web3-vns/node_modules/web3-vns-contract
ln -s $(pwd)/packages/web3-vns-ens $(pwd)/packages/web3-vns/node_modules/web3-vns-ens
ln -s $(pwd)/packages/web3-vns-personal $(pwd)/packages/web3-vns/node_modules/web3-vns-personal
ln -s $(pwd)/packages/web3-vns-iban $(pwd)/packages/web3-vns/node_modules/web3-vns-iban
ln -s $(pwd)/packages/web3-bzz $(pwd)/packages/web3/node_modules/web3-bzz
ln -s $(pwd)/packages/web3-core $(pwd)/packages/web3/node_modules/web3-core
ln -s $(pwd)/packages/web3-vns $(pwd)/packages/web3/node_modules/web3-vns
ln -s $(pwd)/packages/web3-vns-personal $(pwd)/packages/web3/node_modules/web3-vns-personal
ln -s $(pwd)/packages/web3-net $(pwd)/packages/web3/node_modules/web3-net
ln -s $(pwd)/packages/web3-shh $(pwd)/packages/web3/node_modules/web3-shh
ln -s $(pwd)/packages/web3-utils $(pwd)/packages/web3/node_modules/web3-utils
