rd/s/q packages\web3-vns-abi\node_modules\web3-utils 
rd/s/q packages\web3-vns-iban\node_modules\web3-utils 
rd/s/q packages\web3-core-helpers\node_modules\web3-vns-iban 
rd/s/q packages\web3-core-helpers\node_modules\web3-utils 
rd/s/q packages\web3-core-subscriptions\node_modules\web3-core-helpers
rd/s/q packages\web3-providers-http\node_modules\web3-core-helpers
rd/s/q packages\web3-providers-ipc\node_modules\web3-core-helpers
rd/s/q packages\web3-providers-ws\node_modules\web3-core-helpers
rd/s/q packages\web3-core-method\node_modules\web3-core-helpers
rd/s/q packages\web3-core-method\node_modules\web3-core-promievent
rd/s/q packages\web3-core-method\node_modules\web3-core-subscriptions
rd/s/q packages\web3-core-method\node_modules\web3-utils
rd/s/q packages\web3-core-requestmanager\node_modules\web3-core-helpers
rd/s/q packages\web3-core-requestmanager\node_modules\web3-providers-http
rd/s/q packages\web3-core-requestmanager\node_modules\web3-providers-ipc
rd/s/q packages\web3-core-requestmanager\node_modules\web3-providers-ws
rd/s/q packages\web3-core\node_modules\web3-core-helpers
rd/s/q packages\web3-core\node_modules\web3-core-method
rd/s/q packages\web3-core\node_modules\web3-core-requestmanager
rd/s/q packages\web3-core\node_modules\web3-utils
rd/s/q packages\web3-net\node_modules\web3-core
rd/s/q packages\web3-net\node_modules\web3-core-method
rd/s/q packages\web3-net\node_modules\web3-utils
rd/s/q packages\web3-shh\node_modules\web3-core
rd/s/q packages\web3-shh\node_modules\web3-core-method
rd/s/q packages\web3-shh\node_modules\web3-core-subscriptions
rd/s/q packages\web3-shh\node_modules\web3-net
rd/s/q packages\web3-vns-contract\node_modules\web3-core
rd/s/q packages\web3-vns-contract\node_modules\web3-core-helpers
rd/s/q packages\web3-vns-contract\node_modules\web3-core-method
rd/s/q packages\web3-vns-contract\node_modules\web3-core-promievent
rd/s/q packages\web3-vns-contract\node_modules\web3-core-subscriptions
rd/s/q packages\web3-vns-contract\node_modules\web3-utils
rd/s/q packages\web3-vns-contract\node_modules\web3-vns-abi

rd/s/q packages\web3-vns-accounts\node_modules\web3-core
rd/s/q packages\web3-vns-accounts\node_modules\web3-core-helpers
rd/s/q packages\web3-vns-accounts\node_modules\web3-core-method
rd/s/q packages\web3-vns-accounts\node_modules\web3-utils

rd/s/q packages\web3-vns-personal\node_modules\web3-core
rd/s/q packages\web3-vns-personal\node_modules\web3-core-helpers
rd/s/q packages\web3-vns-personal\node_modules\web3-core-method
rd/s/q packages\web3-vns-personal\node_modules\web3-net
rd/s/q packages\web3-vns-personal\node_modules\web3-utils

rd/s/q packages\web3-vns-ens\node_modules\web3-core
rd/s/q packages\web3-vns-ens\node_modules\web3-core-helpers 
rd/s/q packages\web3-vns-ens\node_modules\web3-core-promievent
rd/s/q packages\web3-vns-ens\node_modules\web3-utils
rd/s/q packages\web3-vns-ens\node_modules\web3-vns-abi
rd/s/q packages\web3-vns-ens\node_modules\web3-vns-contract

rd/s/q packages\web3-vns\node_modules\web3-core
rd/s/q packages\web3-vns\node_modules\web3-core-helpers
rd/s/q packages\web3-vns\node_modules\web3-core-method
rd/s/q packages\web3-vns\node_modules\web3-core-subscriptions
rd/s/q packages\web3-vns\node_modules\web3-net
rd/s/q packages\web3-vns\node_modules\web3-utils
rd/s/q packages\web3-vns\node_modules\web3-vns-abi
rd/s/q packages\web3-vns\node_modules\web3-vns-accounts
rd/s/q packages\web3-vns\node_modules\web3-vns-contract
rd/s/q packages\web3-vns\node_modules\web3-vns-ens
rd/s/q packages\web3-vns\node_modules\web3-vns-personal
rd/s/q packages\web3-vns\node_modules\web3-vns-iban

rd/s/q packages\web3\node_modules\web3-bzz
rd/s/q packages\web3\node_modules\web3-core
rd/s/q packages\web3\node_modules\web3-vns
rd/s/q packages\web3\node_modules\web3-vns-personal
rd/s/q packages\web3\node_modules\web3-net
rd/s/q packages\web3\node_modules\web3-shh
rd/s/q packages\web3\node_modules\web3-utils
