rm -rf $(pwd)/packages/web3-vns-abi/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-vns-iban/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-core-helpers/node_modules/web3-vns-iban
rm -rf $(pwd)/packages/web3-core-helpers/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-core-subscriptions/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-providers-http/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-providers-ipc/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-providers-ws/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-core-method/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-core-method/node_modules/web3-core-promievent
rm -rf $(pwd)/packages/web3-core-method/node_modules/web3-core-subscriptions
rm -rf $(pwd)/packages/web3-core-method/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-core-requestmanager/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-core-requestmanager/node_modules/web3-providers-http
rm -rf $(pwd)/packages/web3-core-requestmanager/node_modules/web3-providers-ipc
rm -rf $(pwd)/packages/web3-core-requestmanager/node_modules/web3-providers-ws
rm -rf $(pwd)/packages/web3-core/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-core/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-core/node_modules/web3-core-requestmanager
rm -rf $(pwd)/packages/web3-core/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-net/node_modules/web3-core
rm -rf $(pwd)/packages/web3-net/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-net/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-shh/node_modules/web3-core
rm -rf $(pwd)/packages/web3-shh/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-shh/node_modules/web3-core-subscriptions
rm -rf $(pwd)/packages/web3-shh/node_modules/web3-net
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-core
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-core-promievent
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-core-subscriptions
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-vns-contract/node_modules/web3-vns-abi
rm -rf $(pwd)/packages/web3-vns-accounts/node_modules/web3-core
rm -rf $(pwd)/packages/web3-vns-accounts/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-vns-accounts/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-vns-accounts/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-vns-personal/node_modules/web3-core
rm -rf $(pwd)/packages/web3-vns-personal/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-vns-personal/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-vns-personal/node_modules/web3-net
rm -rf $(pwd)/packages/web3-vns-personal/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-vns-ens/node_modules/web3-core
rm -rf $(pwd)/packages/web3-vns-ens/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-vns-ens/node_modules/web3-core-promievent
rm -rf $(pwd)/packages/web3-vns-ens/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-vns-ens/node_modules/web3-vns-abi
rm -rf $(pwd)/packages/web3-vns-ens/node_modules/web3-vns-contract
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-core
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-core-helpers
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-core-method
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-core-subscriptions
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-net
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-utils
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-vns-abi
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-vns-accounts
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-vns-contract
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-vns-ens
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-vns-personal
rm -rf $(pwd)/packages/web3-vns/node_modules/web3-vns-iban
rm -rf $(pwd)/packages/web3/node_modules/web3-bzz
rm -rf $(pwd)/packages/web3/node_modules/web3-core
rm -rf $(pwd)/packages/web3/node_modules/web3-vns
rm -rf $(pwd)/packages/web3/node_modules/web3-vns-personal
rm -rf $(pwd)/packages/web3/node_modules/web3-net
rm -rf $(pwd)/packages/web3/node_modules/web3-shh
rm -rf $(pwd)/packages/web3/node_modules/web3-utils
